export const ACTIONS = {
  ADD_POST: 'ADD_POST',
  ADD_ALL_POSTS: 'ADD_ALL_POSTS',
  CLEAR_POST: 'CLEAR_POST',
  SEARCH_REQUEST: 'SEARCH_REQUEST',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
};
